### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by Khysnik** [windows93dotnet/sys42#2]
Windows93 has been a serious part of my little introverted life, lol. I was a regular on trollbox, and a myspace OG. Thanks for the release, i'm sure that i will be using this soon ^v^

PS, trollbox source code next? 🙌

**Comment by zo** [comment]
Thanks, this means a lot! 
There is no plan to release trollbox source at the moment.
Also, this is an issue tracker, please use contact@windows93.net for messages like this.
